In [ ]:
import sys
import numpy as np
import pandas as pd

In [2]:
origin = 'datasets/demo.edges'
processed = 'datasets/demo.bin'

In [5]:
df = pd.read_csv(origin, sep=' ', header=None, comment='#')
coo = df.to_numpy()
coo

array([[0, 1],
       [0, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 2]])

In [7]:
nodes = np.unique(coo)
nodes

array([0, 1, 2, 3])

In [8]:
reorder = {}
for i in range(nodes.shape[0]):
    reorder[nodes[i]] = i
# 记录的是每个node重新映射后的排序，重新映射后的排序号作为顶点的新编号
reorder

{0: 0, 1: 1, 2: 2, 3: 3}

In [ ]:
for i in range(coo.shape[0]):
    coo[i][0] = reorder[coo[i][0]]
    coo[i][1] = reorder[coo[i][1]]
# coo更新为新编号计数
print(coo,coo.shape)

[[0 1]
 [0 2]
 [1 3]
 [2 0]
 [2 1]
 [2 3]
 [3 2]] (7, 2)
7


In [ ]:
# (i->j)的组合按照j排序
coo = coo[coo[:,1].argsort()]
coo

array([[2, 0],
       [0, 1],
       [2, 1],
       [0, 2],
       [3, 2],
       [1, 3],
       [2, 3]])

In [ ]:
data = coo.T.astype(np.int32)
"""
[[2, 0, 2, 0, 3, 1, 2],
 [0, 1, 1, 2, 2, 3, 3]]
上面是i,对应下面是j,即i->j边
"""
data

array([[2, 0, 2, 0, 3, 1, 2],
       [0, 1, 1, 2, 2, 3, 3]], dtype=int32)

In [13]:
data.tofile(processed)